### ISSUE TITLE
Arkitektur og løsningsbeskrivelse

### ISSUE THREAD

**Issue by SnorreTE** [digdir/roadmap#162]
## Overordnet beskrivelse

Dette er arbeidet med å utarbeide konseptet, løsningsbeskrivelse og overordnet arkitektur for løsningen.

## Forventet resultat

Løsningsforslag og overordnet arkitektur er utarbeidet og dokumentert.

## Hvordan vil det virke?

Det vil danne grunnlaget og rammene for utviklingsarbeidet som skal legges ned for å implementere Dialogporten.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten/issues/89
```

**Comment by DirkLammering** [comment]
Alle tasks på denne er lukket og progresjonen er på 100% - jeg setter den derfor til lukket - du får åpne den igjen @elsand hvis den fortsatt skal stå som åpen
