### ISSUE TITLE
Sikkerhetstesting

### ISSUE THREAD

**Issue by SnorreTE** [digdir/roadmap#166]
## Overordnet beskrivelse

Det skal foretas sikkerhetstesting før produktet tar i bruk skarpe data

## Forventet resultat

Gjennomført testing vil trolig avstedkomme endringsbehov som da legges inn som issues i de respektive backlogs.

## Hvordan vil det virke?

Fortrinnsvis rigges dette med interne ressurser, men det kan være aktuelt å involvere eksterne leverandører med spisskompetanse på f.eks. penetrasjonstesting.

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/dialogporten/issues/82
```

**Comment by DirkLammering** [comment]
Kanskje dele opp i egen ytelse og egen sikkerhet ?
