### ISSUE TITLE
Varsling - Påminnelse

### ISSUE THREAD

**Issue by aas-tbuar** [digdir/roadmap#177]
## Overordnet beskrivelse
Ordinære varsel med sendetidspunkt frem i tid

## Hvordan skal det fungere?
Implementeres som ordinære varsel med sendetidspunkt frem i tid. Det som skiller påminnelser fra andre varsel, er at de kan stoppes hvis de anses som unødvendig. Det som utvikles her er en mekanisme for å sjekke forutsetningene for utsendelse av varsel. 

For eksempel: “er melding ulest” 

I første omgang må forutsetningene være basert på instanser i Altinn 3, men det skal lages på en måte som gjør det enkelt og utvide med flere kilder.  

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-notifications/issues/204
```

**Comment by SandGrainOne** [comment]
Påminnelser må bli veldig anderledes i Altinn 3 enn i Altinn 2 på grunn av manglende tilgang til kilde data. Det er vanskelig for Varsel å vite status på en melding, dialog, eller app instans uten å spørre kildesystemet. I første omgang blir det derfor opp til kildesystemene selv å reigstrere påminnelser i form av nye varsel til samme aktør.
