### ISSUE TITLE
Støtte underskjema i Altinn 3 tjenester

### ISSUE THREAD

**Issue by RonnyB71** [digdir/roadmap#290]
## Overordnet beskrivelse
En tjeneste, eller en app, i Altinn 3 har gjerne ett skjema. Ett skjema kan, i tillegg til skjemadata, ha vedlegg i form av ulike filer (word, pdf, bilder, video etc.). Underskjema, eller vedleggskjema, er et eget skjema som supplerer hovedskjema i tjenesten med egne skjemadata og evt. vedlegg. Et eksempel kan være en tjeneste som rapporterer konserndata. Hovedskjema inneholder data tilknyttet konsernet, mens underskjema representerer ett spesifikt selskap i konsernet. Man vil da typisk ha ett underskjema per selskap.

## Forventet resultat
Tilby tilsvarende funksjonalitet som de tjenestene som benytter underskjema i Altinn 2 i dag slik at migrering av disse er mulig. Enkel konfigurering av hvilke underskjema som er tilgjengelig og hvordan disse skal vises for sluttbruker.

## Hvordan vil det virke?
- [ ] Et underskjema vil ha alle de samme mulighetene som et hovedskjema med tanke på sideinndeling, bruk av komponenter, vis/skjul logikk, validering etc. 
- [ ] Et underskjema vil ha sin egen datamodell og sin egen layout for hvordan skjema skal fremstå for brukeren. I første versjon skal eksisterende sideoppbygging benyttes, men i fremtiden skal det være mulig å velge alternative visninger for enkle underskjema f. eks. en overlay eller embedded direkte i skjema. Sistnevnte er kanskje mest aktuelt i kombinasjon med dashboard funksjonalitet (planlagt i Altinn/altinn-studio#83)
- [ ] Data for underskjema lagres for seg selv og får et eget dataelement
- [ ] Man kan opprette mange underskjema av samme type og man kan ha flere forskjellige typer underskjema. 
- [ ] Fra hovedskjema kan man legge til underskjema gjennom en egen komponent som holder kontroll på underskjemaene. 
- [ ] Man kan enten ha én underskjemakomponent som holder kontroll på alle underskjemaene uavhengig av type, eller man kan ha flere underskjemakomponenter som holder kontroll på sine egne typer. 
- [ ] Det skal være mulig å styre krav til hvor mange underskjema man skal ha av en gitt type (minimum og maksimum).
- [ ] Det skal være mulig å lukke redigeringen av et underskjema, selv med valideringsfeil, og fortsette redigeringen på et senere tidspunkt.
- [ ] Innsening av hovedskjema med tilhørende underskjema må validere alle skjema før innsending kan skje.
- [ ] Det skal være mulig å ha en oppsummeringsside som henter data fra både hovedskjema og underskjema.
- [ ] Uttrykk i underskjema må kunne referere til data fra hovedskjema for vis/skjul logikk
- [ ] Det skal være mulig å lage egen PDF for underskjema
- [ ] Det skal være mulig å inkludere data fra underskjema i PDF (hvis man bare ønsker en PDF)
- [ ] Det skal være mulig å inkludere underskjema i grunnlaget det signeres på.
- [ ] Ulike navn på PDF'er

## Gjennomføring
```[tasklist]
### Oppgaver
- [ ] https://github.com/Altinn/app-template-dotnet/issues/25
- [ ] https://github.com/Altinn/altinn-studio/issues/13410
```
```[tasklist]
### Relaterte oppgaver til vurdering
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/142
- [ ] https://github.com/Altinn/app-lib-dotnet/issues/561
```

```[tasklist]
### Avhengigheter
- [ ] https://github.com/digdir/roadmap/issues/136
```

**Comment by benteSSB** [comment]
Det bør vere mogleg å delegera kvart enkelt underskjema.

**Comment by hanneline** [comment]
"Det skal være mulig å styre krav til hvor mange underskjema man skal ha av en gitt type (minimum og maksimum)."

Dette må kunne styres dynamisk utfra valg bruker har gjort i hovedskjema.

**Comment by olemartinorg** [comment]
Jeg tror også man må kunne dyplenke til en side i et underskjema. Det vil si, hvilket underskjema man står i, og hvilken side man står på der, bør ligge i URLen slik at fremover/tilbake-knappene i nettleseren bør fungere.
