### ISSUE TITLE
Integrasjon med andre produkter

### ISSUE THREAD

**Issue by nkylstad** [digdir/roadmap#417]
## Overordnet beskrivelse

> OBS! Dette elementet er under arbeid. Det er mulig elementet bør splittes opp i flere elementer, ett per produkt.

Tilgjengeliggjøre de andre Altinn-produktene som integrerte deler av an app. 

- Melding (1 - 3 mnd)
- Formidling (1 - 3 mnd)
- Varsling (1 - 3 mnd)
- Autorisasjon (1 - 3 mnd)
   - Tilgangsgrupper 
- DAN
   - Prefill, konfig (ikke i programmet) 
- eSignering
    - Er på listen, men foreløpig ikke behov for. 

## Forventet resultat
Det skal være mulig å integrere direkte mot de andre produktene i Altinn-porteføljen fra en Altinn Studio app. 

### Eksempler:
- Dra inn en melding som en del av prosessen til en app
- Tilby en Formidlings-komponent for opp-/nedlasting i en app
- Konfigurasjon for automatisk trigger av varsling
- Publisering av app-policy til ressursregister

## Gjennomføring

**Comment by RonnyB71** [comment]
Lukkes, egne veikart saker er opprettet for hver integrasjon med andre produkter.
