### ISSUE TITLE
"Følg saken" referanse

### ISSUE THREAD

**Issue by Jepresterud** [digdir/roadmap#9]
korleis følge saker gjennom fleire etatar og nivå?

"Følg saken" har vore eit ynske gjennom heile prosjektet

Funkjsonalitet i API, hvor de kan ta oppslag i en eksisterende sak som er relevant, og lenke disse sammen før overføring av ny sak.

**Comment by talisker77** [comment]
Hvor er API dokumentert?
Hvor ligger dette API'et i staging/test miljø?
